org: bravodev
app: power2go
service: django-graphQL-api
useDotenv: true

provider:
  name: aws
  region: ${env:AWS_REGION_NAME, 'us-east-1'}
  runtime: python3.9
  stage: ${opt:stage, 'stg'}
  timeout: 30
  memorySize: 2048
  deploymentBucket:
    name: bravosuperbucket 

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-dotenv-plugin
functions:
  api:  
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

custom:
  wsgi:
    app: myapi.wsgi.application

package:
  exclude:
    - venv/**
    - __pycache__/*
    - node_modules/**
    - README.md
    - pytest.ini
    - conftest.py
    - .venv
    - .venv.example
    - package.json
    - package-lock.json